export const bankTypes = {
  "050000": {
    name: "Хаан банк",
    color: "#2C8F40",
    style: "Card2",
    biccode: "AGMOMNUB",
    priority: 20,
    iconName: "ic24-bank-khan",
    bankcode: "050000",
    ePin: true,
  },
  150000: {
    name: "Голомт банк",
    color: "#1062AC",
    style: "Card3",
    biccode: "GLMTMNUB",
    priority: 19,
    iconName: "ic24-bank-golomt",
    bankcode: 150000,
    ePin: true,
  },
  340000: {
    name: "Төрийн банк",
    color: "#00AEEF",
    style: "Card6",
    biccode: "STBMMNUB",
    priority: 18,
    iconName: "ic24-bank-state",
    bankcode: 340000,
    ePin: true,
  },
  320000: {
    name: "Хас банк",
    color: "#FF6633",
    style: "Card4",
    biccode: "CAXBMNUB",
    priority: 17,
    iconName: "ic24-bank-khas",
    bankcode: 320000,
    ePin: true,
  },
  "040000": {
    name: "Худалдаа хөгжлийн банк",
    color: "#0389FF",
    style: "Card11",
    biccode: "TDBMMNUB",
    priority: 16,
    iconName: "ic24-bank-tdb",
    bankcode: "040000",
    ePin: true,
  },
  500000: {
    name: "Мобифинанс ББСБ",
    color: "red",
    style: "Card14",
    biccode: "MOBIMNUB",
    priority: 15,
    iconName: "ic24-bank-mobi",
    bankcode: 500000,
  },
  380000: {
    name: "Богд банк",
    color: "red",
    style: "Card15",
    biccode: "BOGDMNUB",
    priority: 14,
    iconName: "ic24-bank-bogd",
    bankcode: 380000,
  },
  190000: {
    name: "Тээвэр хөгжлийн банк",
    color: "red",
    style: "Card12",
    biccode: "TRDMMNUB",
    priority: 13,
    iconName: "ic24-bank-trans",
    bankcode: 190000,
  },
  210000: {
    name: "Ариг банк",
    color: "#1062AC",
    style: "Card5",
    biccode: "ARGBMNUB",
    priority: 12,
    iconName: "ic24-bank-arig",
    bankcode: 210000,
  },
  300000: {
    name: "Капитрон банк",
    color: "red",
    style: "Card10",
    biccode: "CPITMNUB",
    priority: 11,
    iconName: "ic24-bank-capitron",
    bankcode: 300000,
  },
  290000: {
    name: "Үндэсний хөрөнгө оруулалтын банк",
    color: "red",
    style: "Card9",
    biccode: "NAIMMNUB",
    priority: 10,
    iconName: "ic24-bank-nibank",
    bankcode: 290000,
  },
  520000: {
    name: "Ард кредит ББСБ",
    color: "red",
    style: "Card13",
    biccode: "ARDBMNUB",
    priority: 9,
    iconName: "ic24-bank-ard",
    bankcode: 520000,
  },
  330000: {
    name: "Чингис хаан банк",
    color: "red",
    style: "Card7",
    biccode: "CHKHMNUB",
    priority: 8,
    iconName: "ic24-bank-chingis",
    bankcode: 330000,
  },
  390000: {
    name: "М банк",
    color: "#2C8F40",
    style: "Card8",
    biccode: "MBNKMNUB",
    priority: 8,
    iconName: "ic24-bank-mbank",
    bankcode: 390000,
  },
  220000: {
    name: "Кредит банк",
    color: "red",
    style: "Card8",
    biccode: "CRMNMNUB",
    priority: 0,
    hidden: true,
    iconName: "ic24-bank-credit",
    bankcode: 220000,
  },
  510000: {
    name: "Hipay",
    color: "#E32768",
    style: "Card1",
    biccode: "HPSMMNUB",
    priority: 2,
    hidden: true,
    iconName: "",
    bankcode: 510000,
  },
  530000: {
    name: "Инвескор",
    color: "red",
    style: "Card14",
    biccode: "INVPMNUB",
    priority: -1,
    hidden: true,
    iconName: "ic24-bank-invescore",
    bankcode: 530000,
  },
  950000: {
    name: "Үнэт цаасны төвлөрсөн хадгаламжийн төв",
    color: "red",
    biccode: "CSDMMNUB",
    hidden: false,
    iconName: "ic24-utstht-black",
    bankcode: 950000,
  },
  540000: {
    name: "Netcapital",
    color: "#1062AC",
    style: "Card1",
    biccode: "NCFGMNUB",
    priority: 22,
    hidden: true,
    iconName: "ic24-bank-invescore",
    bankcode: 540000,
  },
  550000: {
    name: "Дата Бэйнк",
    color: "#1062AC",
    style: "Card1",
    biccode: "DTBKMNUB",
    priority: 23,
    iconName: "ic24-bank-invescore",
    bankcode: 550000,
  },
};
