export const travelsimCountries = [
  {
    code: "US",
    en: "United States",
    mn: "Америкийн Нэгдсэн Улс",
    src: "https://flagcdn.com/us.svg",
  },
  {
    code: "KR",
    en: "South Korea",
    mn: "Өмнөд Солонгос",
    src: "https://flagcdn.com/kr.svg",
  },
  { code: "CN", en: "China", mn: "Хятад", src: "https://flagcdn.com/cn.svg" },
  { code: "JP", en: "Japan", mn: "Япон", src: "https://flagcdn.com/jp.svg" },
  { code: "CA", en: "Canada", mn: "Канад", src: "https://flagcdn.com/ca.svg" },
  { code: "RU", en: "Russia", mn: "Орос", src: "https://flagcdn.com/ru.svg" },
  {
    code: "GB",
    en: "United Kingdom, Great Britain",
    mn: "Их Британи",
    src: "https://flagcdn.com/gb.svg",
  },
  {
    code: "DE",
    en: "Germany",
    mn: "Герман",
    src: "https://flagcdn.com/de.svg",
  },
  { code: "TR", en: "Turkey", mn: "Турк", src: "https://flagcdn.com/tr.svg" },
  { code: "IN", en: "India", mn: "Энэтхэг", src: "https://flagcdn.com/in.svg" },
  { code: "FR", en: "France", mn: "Франц", src: "https://flagcdn.com/fr.svg" },
  { code: "SE", en: "Sweden", mn: "Швед", src: "https://flagcdn.com/se.svg" },
  {
    code: "CH",
    en: "Switzerland",
    mn: "Швейцар",
    src: "https://flagcdn.com/ch.svg",
  },

  { code: "IT", en: "Italy", mn: "Итали", src: "https://flagcdn.com/it.svg" },
  {
    code: "AU",
    en: "Australia",
    mn: "Австрали",
    src: "https://flagcdn.com/au.svg",
  },
  { code: "ES", en: "Spain", mn: "Испани", src: "https://flagcdn.com/es.svg" },

  { code: "BR", en: "Brazil", mn: "Бразил", src: "https://flagcdn.com/br.svg" },

  { code: "MX", en: "Mexico", mn: "Мексик", src: "https://flagcdn.com/mx.svg" },

  { code: "SY", en: "Syria", mn: "Сири", src: "https://flagcdn.com/sy.svg" },
  {
    code: "TW",
    en: "Taiwan",
    mn: "Тайвань",
    src: "https://flagcdn.com/tw.svg",
  },
  {
    code: "ZA",
    en: "South Africa",
    mn: "Өмнөд Африк",
    src: "https://flagcdn.com/za.svg",
  },
  {
    code: "NG",
    en: "Nigeria",
    mn: "Нигери",
    src: "https://flagcdn.com/ng.svg",
  },
  {
    code: "AR",
    en: "Argentina",
    mn: "Аргентин",
    src: "https://flagcdn.com/ar.svg",
  },
  {
    code: "SA",
    en: "Saudi Arabia",
    mn: "Саудын Араб",
    src: "https://flagcdn.com/sa.svg",
  },
  { code: "EG", en: "Egypt", mn: "Египет", src: "https://flagcdn.com/eg.svg" },
  {
    code: "AF",
    en: "Afghanistan",
    mn: "Афганистан",
    src: "https://flagcdn.com/af.svg",
  },
  {
    code: "AL",
    en: "Albania",
    mn: "Албани",
    src: "https://flagcdn.com/al.svg",
  },
  { code: "DZ", en: "Algeria", mn: "Алжир", src: "https://flagcdn.com/dz.svg" },
  {
    code: "AS",
    en: "American Samoa",
    mn: "Америкийн Самоа",
    src: "https://flagcdn.com/as.svg",
  },
  {
    code: "AD",
    en: "Andorra",
    mn: "Андорра",
    src: "https://flagcdn.com/ad.svg",
  },
  { code: "AO", en: "Angola", mn: "Ангол", src: "https://flagcdn.com/ao.svg" },
  {
    code: "AI",
    en: "Anguilla",
    mn: "Ангилья",
    src: "https://flagcdn.com/ai.svg",
  },
  {
    code: "AQ",
    en: "Antarctica",
    mn: "Антарктид",
    src: "https://flagcdn.com/aq.svg",
  },
  {
    code: "AG",
    en: "Antigua and Barbuda",
    mn: "Антигуа ба Барбуда",
    src: "https://flagcdn.com/ag.svg",
  },
  {
    code: "AM",
    en: "Armenia",
    mn: "Армени",
    src: "https://flagcdn.com/am.svg",
  },
  { code: "AW", en: "Aruba", mn: "Аруба", src: "https://flagcdn.com/aw.svg" },
  {
    code: "AT",
    en: "Austria",
    mn: "Австри",
    src: "https://flagcdn.com/at.svg",
  },
  {
    code: "AZ",
    en: "Azerbaijan",
    mn: "Азербайжан",
    src: "https://flagcdn.com/az.svg",
  },
  {
    code: "BS",
    en: "Bahamas",
    mn: "Багамын арлууд",
    src: "https://flagcdn.com/bs.svg",
  },
  {
    code: "BH",
    en: "Bahrain",
    mn: "Бахрейн",
    src: "https://flagcdn.com/bh.svg",
  },
  {
    code: "BD",
    en: "Bangladesh",
    mn: "Бангладеш",
    src: "https://flagcdn.com/bd.svg",
  },
  {
    code: "BB",
    en: "Barbados",
    mn: "Барбадос",
    src: "https://flagcdn.com/bb.svg",
  },
  {
    code: "BY",
    en: "Belarus",
    mn: "Беларусь",
    src: "https://flagcdn.com/by.svg",
  },
  {
    code: "BE",
    en: "Belgium",
    mn: "Бельги",
    src: "https://flagcdn.com/be.svg",
  },
  { code: "BZ", en: "Belize", mn: "Белиз", src: "https://flagcdn.com/bz.svg" },
  { code: "BJ", en: "Benin", mn: "Бенин", src: "https://flagcdn.com/bj.svg" },
  {
    code: "BM",
    en: "Bermuda",
    mn: "Бермуд",
    src: "https://flagcdn.com/bm.svg",
  },
  { code: "BT", en: "Bhutan", mn: "Бутан", src: "https://flagcdn.com/bt.svg" },
  {
    code: "BO",
    en: "Bolivia",
    mn: "Боливи",
    src: "https://flagcdn.com/bo.svg",
  },
  {
    code: "BQ",
    en: "Bonaire",
    mn: "Бонэйр",
    src: "https://flagcdn.com/bq.svg",
  },
  {
    code: "BA",
    en: "Bosnia and Herzegovina",
    mn: "Босни ба Херцеговина",
    src: "https://flagcdn.com/ba.svg",
  },
  {
    code: "BW",
    en: "Botswana",
    mn: "Ботсван",
    src: "https://flagcdn.com/bw.svg",
  },
  {
    code: "BV",
    en: "Bouvet Island",
    mn: "Буве арал",
    src: "https://flagcdn.com/bv.svg",
  },
  {
    code: "IO",
    en: "British Indian Ocean Territory",
    mn: "Британийн Энэтхэгийн далайн бүс",
    src: "https://flagcdn.com/io.svg",
  },
  {
    code: "VG",
    en: "British Virgin Islands",
    mn: "Британийн Виржинийн арлууд",
    src: "https://flagcdn.com/vg.svg",
  },
  { code: "BN", en: "Brunei", mn: "Бруней", src: "https://flagcdn.com/bn.svg" },
  {
    code: "BG",
    en: "Bulgaria",
    mn: "Болгар",
    src: "https://flagcdn.com/bg.svg",
  },
  {
    code: "BF",
    en: "Burkina Faso",
    mn: "Буркина Фасо",
    src: "https://flagcdn.com/bf.svg",
  },
  {
    code: "BI",
    en: "Burundi",
    mn: "Бурунди",
    src: "https://flagcdn.com/bi.svg",
  },
  {
    code: "CV",
    en: "Cabo Verde",
    mn: "Кабо-Верде",
    src: "https://flagcdn.com/cv.svg",
  },
  {
    code: "KH",
    en: "Cambodia",
    mn: "Камбож",
    src: "https://flagcdn.com/kh.svg",
  },
  {
    code: "CM",
    en: "Cameroon",
    mn: "Камерун",
    src: "https://flagcdn.com/cm.svg",
  },
  {
    code: "KY",
    en: "Cayman Islands",
    mn: "Кайманы арлууд",
    src: "https://flagcdn.com/ky.svg",
  },
  {
    code: "CF",
    en: "Central African Republic",
    mn: "Төв Африкийн Бүгд Найрамдах Улс",
    src: "https://flagcdn.com/cf.svg",
  },
  { code: "TD", en: "Chad", mn: "Чад", src: "https://flagcdn.com/td.svg" },
  { code: "CL", en: "Chile", mn: "Чили", src: "https://flagcdn.com/cl.svg" },
  {
    code: "CO",
    en: "Colombia",
    mn: "Колумб",
    src: "https://flagcdn.com/co.svg",
  },
  {
    code: "KM",
    en: "Comoros",
    mn: "Коморос",
    src: "https://flagcdn.com/km.svg",
  },
  { code: "CG", en: "Congo", mn: "Конго", src: "https://flagcdn.com/cg.svg" },
  {
    code: "CD",
    en: "Democratic Republic of the Congo",
    mn: "Конго Найрамдал Улс",
    src: "https://flagcdn.com/cd.svg",
  },
  {
    code: "CK",
    en: "Cook Islands",
    mn: "Кук арлууд",
    src: "https://flagcdn.com/ck.svg",
  },
  {
    code: "CR",
    en: "Costa Rica",
    mn: "Коста-Рика",
    src: "https://flagcdn.com/cr.svg",
  },
  {
    code: "HR",
    en: "Croatia",
    mn: "Хорват",
    src: "https://flagcdn.com/hr.svg",
  },
  { code: "CU", en: "Cuba", mn: "Куба", src: "https://flagcdn.com/cu.svg" },
  {
    code: "CW",
    en: "Curaçao",
    mn: "Кюрасао",
    src: "https://flagcdn.com/cw.svg",
  },
  { code: "CY", en: "Cyprus", mn: "Кипр", src: "https://flagcdn.com/cy.svg" },
  {
    code: "CZ",
    en: "Czech Republic",
    mn: "Чех",
    src: "https://flagcdn.com/cz.svg",
  },
  { code: "DK", en: "Denmark", mn: "Дани", src: "https://flagcdn.com/dk.svg" },
  {
    code: "DJ",
    en: "Djibouti",
    mn: "Джибути",
    src: "https://flagcdn.com/dj.svg",
  },
  {
    code: "DM",
    en: "Dominica",
    mn: "Доминика",
    src: "https://flagcdn.com/dm.svg",
  },
  {
    code: "DO",
    en: "Dominican Republic",
    mn: "Доминиканы Найрамдал Улс",
    src: "https://flagcdn.com/do.svg",
  },
  {
    code: "EC",
    en: "Ecuador",
    mn: "Эквадор",
    src: "https://flagcdn.com/ec.svg",
  },
  {
    code: "SV",
    en: "El Salvador",
    mn: "Эль Сальвадор",
    src: "https://flagcdn.com/sv.svg",
  },
  {
    code: "GQ",
    en: "Equatorial Guinea",
    mn: "Экваторын Гвиней",
    src: "https://flagcdn.com/gq.svg",
  },
  {
    code: "ER",
    en: "Eritrea",
    mn: "Эритрей",
    src: "https://flagcdn.com/er.svg",
  },
  { code: "EE", en: "Estonia", mn: "Эстон", src: "https://flagcdn.com/ee.svg" },
  {
    code: "SZ",
    en: "Eswatini",
    mn: "Эсватини",
    src: "https://flagcdn.com/sz.svg",
  },
  {
    code: "ET",
    en: "Ethiopia",
    mn: "Этиоп",
    src: "https://flagcdn.com/et.svg",
  },
  {
    code: "FK",
    en: "Falkland Islands",
    mn: "Фолклендийн арлууд",
    src: "https://flagcdn.com/fk.svg",
  },
  {
    code: "FO",
    en: "Faroe Islands",
    mn: "Фароэ арлууд",
    src: "https://flagcdn.com/fo.svg",
  },
  { code: "FJ", en: "Fiji", mn: "Фижи", src: "https://flagcdn.com/fj.svg" },
  {
    code: "FI",
    en: "Finland",
    mn: "Финланд",
    src: "https://flagcdn.com/fi.svg",
  },
  {
    code: "GF",
    en: "French Guiana",
    mn: "Францын Гайана",
    src: "https://flagcdn.com/gf.svg",
  },
  {
    code: "PF",
    en: "French Polynesia",
    mn: "Францын Полинез",
    src: "https://flagcdn.com/pf.svg",
  },
  {
    code: "TF",
    en: "French Southern Territories",
    mn: "Францын Хойд Францын талд",
    src: "https://flagcdn.com/tf.svg",
  },
  { code: "GA", en: "Gabon", mn: "Габон", src: "https://flagcdn.com/ga.svg" },
  { code: "GM", en: "Gambia", mn: "Гамби", src: "https://flagcdn.com/gm.svg" },
  { code: "GE", en: "Georgia", mn: "Гүрж", src: "https://flagcdn.com/ge.svg" },
  { code: "GH", en: "Ghana", mn: "Гана", src: "https://flagcdn.com/gh.svg" },
  {
    code: "GI",
    en: "Gibraltar",
    mn: "Гибралтар",
    src: "https://flagcdn.com/gi.svg",
  },
  { code: "GR", en: "Greece", mn: "Грек", src: "https://flagcdn.com/gr.svg" },
  {
    code: "GL",
    en: "Greenland",
    mn: "Халимаг",
    src: "https://flagcdn.com/gl.svg",
  },
  {
    code: "GD",
    en: "Grenada",
    mn: "Гренада",
    src: "https://flagcdn.com/gd.svg",
  },
  {
    code: "GP",
    en: "Guadeloupe",
    mn: "Гваделуп",
    src: "https://flagcdn.com/gp.svg",
  },
  { code: "GU", en: "Guam", mn: "Гуам", src: "https://flagcdn.com/gu.svg" },
  {
    code: "GT",
    en: "Guatemala",
    mn: "Гватемал",
    src: "https://flagcdn.com/gt.svg",
  },
  {
    code: "GG",
    en: "Guernsey",
    mn: "Гернси",
    src: "https://flagcdn.com/gg.svg",
  },
  { code: "GN", en: "Guinea", mn: "Гвиней", src: "https://flagcdn.com/gn.svg" },
  {
    code: "GW",
    en: "Guinea-Bissau",
    mn: "Гвиней-Биссау",
    src: "https://flagcdn.com/gw.svg",
  },
  { code: "GY", en: "Guyana", mn: "Гайана", src: "https://flagcdn.com/gy.svg" },
  { code: "HT", en: "Haiti", mn: "Гаити", src: "https://flagcdn.com/ht.svg" },
  {
    code: "HM",
    en: "Heard Island and McDonald Islands",
    mn: "Херд ба Макдоналд арлууд",
    src: "https://flagcdn.com/hm.svg",
  },
  {
    code: "VA",
    en: "Holy See",
    mn: "Өөрийн хаана",
    src: "https://flagcdn.com/va.svg",
  },
  {
    code: "HN",
    en: "Honduras",
    mn: "Гондурас",
    src: "https://flagcdn.com/hn.svg",
  },
  {
    code: "HK",
    en: "Hong Kong",
    mn: "Хонг Конг",
    src: "https://flagcdn.com/hk.svg",
  },
  { code: "HU", en: "Hungary", mn: "Унгар", src: "https://flagcdn.com/hu.svg" },
  {
    code: "IS",
    en: "Iceland",
    mn: "Исланд",
    src: "https://flagcdn.com/is.svg",
  },
  {
    code: "ID",
    en: "Indonesia",
    mn: "Индонез",
    src: "https://flagcdn.com/id.svg",
  },
  { code: "IR", en: "Iran", mn: "Иран", src: "https://flagcdn.com/ir.svg" },
  { code: "IQ", en: "Iraq", mn: "Ирак", src: "https://flagcdn.com/iq.svg" },
  {
    code: "IE",
    en: "Ireland",
    mn: "Ирланд",
    src: "https://flagcdn.com/ie.svg",
  },
  {
    code: "IM",
    en: "Isle of Man",
    mn: "Мэн Арал",
    src: "https://flagcdn.com/im.svg",
  },
  {
    code: "IL",
    en: "Israel",
    mn: "Израиль",
    src: "https://flagcdn.com/il.svg",
  },
  {
    code: "CI",
    en: "Ivory Coast",
    mn: "Албан шаргуу",
    src: "https://flagcdn.com/ci.svg",
  },
  {
    code: "JM",
    en: "Jamaica",
    mn: "Ямайка",
    src: "https://flagcdn.com/jm.svg",
  },
  { code: "JE", en: "Jersey", mn: "Жерси", src: "https://flagcdn.com/je.svg" },
  { code: "JO", en: "Jordan", mn: "Йордан", src: "https://flagcdn.com/jo.svg" },
  {
    code: "KZ",
    en: "Kazakhstan",
    mn: "Казахстан",
    src: "https://flagcdn.com/kz.svg",
  },
  { code: "KE", en: "Kenya", mn: "Кени", src: "https://flagcdn.com/ke.svg" },
  {
    code: "KI",
    en: "Kiribati",
    mn: "Кирибати",
    src: "https://flagcdn.com/ki.svg",
  },
  { code: "KW", en: "Kuwait", mn: "Кувейт", src: "https://flagcdn.com/kw.svg" },
  {
    code: "KG",
    en: "Kyrgyzstan",
    mn: "Кыргызстан",
    src: "https://flagcdn.com/kg.svg",
  },
  { code: "LA", en: "Laos", mn: "Лаос", src: "https://flagcdn.com/la.svg" },
  { code: "LV", en: "Latvia", mn: "Латви", src: "https://flagcdn.com/lv.svg" },
  { code: "LB", en: "Lebanon", mn: "Ливан", src: "https://flagcdn.com/lb.svg" },
  {
    code: "LS",
    en: "Lesotho",
    mn: "Лесото",
    src: "https://flagcdn.com/ls.svg",
  },
  {
    code: "LR",
    en: "Liberia",
    mn: "Либери",
    src: "https://flagcdn.com/lr.svg",
  },
  { code: "LY", en: "Libya", mn: "Ливи", src: "https://flagcdn.com/ly.svg" },
  {
    code: "LI",
    en: "Liechtenstein",
    mn: "Лихтенштейн",
    src: "https://flagcdn.com/li.svg",
  },
  {
    code: "LT",
    en: "Lithuania",
    mn: "Литва",
    src: "https://flagcdn.com/lt.svg",
  },
  {
    code: "LU",
    en: "Luxembourg",
    mn: "Люксембург",
    src: "https://flagcdn.com/lu.svg",
  },
  { code: "MO", en: "Macau", mn: "Макао", src: "https://flagcdn.com/mo.svg" },
  {
    code: "MG",
    en: "Madagascar",
    mn: "Мадагаскар",
    src: "https://flagcdn.com/mg.svg",
  },
  { code: "MW", en: "Malawi", mn: "Малави", src: "https://flagcdn.com/mw.svg" },
  {
    code: "MY",
    en: "Malaysia",
    mn: "Малайз",
    src: "https://flagcdn.com/my.svg",
  },
  {
    code: "MV",
    en: "Maldives",
    mn: "Мальдив",
    src: "https://flagcdn.com/mv.svg",
  },
  { code: "ML", en: "Mali", mn: "Мали", src: "https://flagcdn.com/ml.svg" },
  { code: "MT", en: "Malta", mn: "Мальта", src: "https://flagcdn.com/mt.svg" },
  {
    code: "MH",
    en: "Marshall Islands",
    mn: "Маршалл арлууд",
    src: "https://flagcdn.com/mh.svg",
  },
  {
    code: "MQ",
    en: "Martinique",
    mn: "Мартиник",
    src: "https://flagcdn.com/mq.svg",
  },
  {
    code: "MR",
    en: "Mauritania",
    mn: "Мавритани",
    src: "https://flagcdn.com/mr.svg",
  },
  {
    code: "MU",
    en: "Mauritius",
    mn: "Мавритус",
    src: "https://flagcdn.com/mu.svg",
  },
  {
    code: "YT",
    en: "Mayotte",
    mn: "Майотта",
    src: "https://flagcdn.com/yt.svg",
  },
  {
    code: "FM",
    en: "Micronesia",
    mn: "Микронези",
    src: "https://flagcdn.com/fm.svg",
  },
  {
    code: "MD",
    en: "Moldova",
    mn: "Молдова",
    src: "https://flagcdn.com/md.svg",
  },
  { code: "MC", en: "Monaco", mn: "Монако", src: "https://flagcdn.com/mc.svg" },
  {
    code: "MN",
    en: "Mongolia",
    mn: "Монгол",
    src: "https://flagcdn.com/mn.svg",
  },
  {
    code: "ME",
    en: "Montenegro",
    mn: "Монтенегро",
    src: "https://flagcdn.com/me.svg",
  },
  {
    code: "MS",
    en: "Montserrat",
    mn: "Монтсеррат",
    src: "https://flagcdn.com/ms.svg",
  },
  {
    code: "MA",
    en: "Morocco",
    mn: "Марокко",
    src: "https://flagcdn.com/ma.svg",
  },
  {
    code: "MZ",
    en: "Mozambique",
    mn: "Мозамбик",
    src: "https://flagcdn.com/mz.svg",
  },
  {
    code: "MM",
    en: "Myanmar",
    mn: "Мьянмар",
    src: "https://flagcdn.com/mm.svg",
  },
  {
    code: "NA",
    en: "Namibia",
    mn: "Намиби",
    src: "https://flagcdn.com/na.svg",
  },
  { code: "NR", en: "Nauru", mn: "Науру", src: "https://flagcdn.com/nr.svg" },
  { code: "NP", en: "Nepal", mn: "Непал", src: "https://flagcdn.com/np.svg" },
  {
    code: "NL",
    en: "Netherlands",
    mn: "Нидерланд",
    src: "https://flagcdn.com/nl.svg",
  },
  {
    code: "NC",
    en: "New Caledonia",
    mn: "Шинэ Каледони",
    src: "https://flagcdn.com/nc.svg",
  },
  {
    code: "NZ",
    en: "New Zealand",
    mn: "Шинэ Зеланд",
    src: "https://flagcdn.com/nz.svg",
  },
  {
    code: "NI",
    en: "Nicaragua",
    mn: "Никарагуа",
    src: "https://flagcdn.com/ni.svg",
  },
  { code: "NE", en: "Niger", mn: "Нигер", src: "https://flagcdn.com/ne.svg" },
  { code: "NU", en: "Niue", mn: "Ниуэ", src: "https://flagcdn.com/nu.svg" },
  {
    code: "NF",
    en: "Norfolk Island",
    mn: "Норфолк арал",
    src: "https://flagcdn.com/nf.svg",
  },
  {
    code: "KP",
    en: "North Korea",
    mn: "Хойд Солонгос",
    src: "https://flagcdn.com/kp.svg",
  },
  {
    code: "MK",
    en: "North Macedonia",
    mn: "Хойд Македон",
    src: "https://flagcdn.com/mk.svg",
  },
  {
    code: "MP",
    en: "Northern Mariana Islands",
    mn: "Хойд Марианы арлууд",
    src: "https://flagcdn.com/mp.svg",
  },
  {
    code: "NO",
    en: "Norway",
    mn: "Норвеги",
    src: "https://flagcdn.com/no.svg",
  },
  { code: "OM", en: "Oman", mn: "Оман", src: "https://flagcdn.com/om.svg" },
  {
    code: "PK",
    en: "Pakistan",
    mn: "Пакистан",
    src: "https://flagcdn.com/pk.svg",
  },
  { code: "PW", en: "Palau", mn: "Палау", src: "https://flagcdn.com/pw.svg" },
  {
    code: "PS",
    en: "Palestine",
    mn: "Палестин",
    src: "https://flagcdn.com/ps.svg",
  },
  { code: "PA", en: "Panama", mn: "Панам", src: "https://flagcdn.com/pa.svg" },
  {
    code: "PG",
    en: "Papua New Guinea",
    mn: "Папуа Шинэ Гвиней",
    src: "https://flagcdn.com/pg.svg",
  },
  {
    code: "PY",
    en: "Paraguay",
    mn: "Парагвай",
    src: "https://flagcdn.com/py.svg",
  },
  { code: "PE", en: "Peru", mn: "Перу", src: "https://flagcdn.com/pe.svg" },
  {
    code: "PH",
    en: "Philippines",
    mn: "Филиппин",
    src: "https://flagcdn.com/ph.svg",
  },
  {
    code: "PN",
    en: "Pitcairn Islands",
    mn: "Питкэрн арлууд",
    src: "https://flagcdn.com/pn.svg",
  },
  { code: "PL", en: "Poland", mn: "Польш", src: "https://flagcdn.com/pl.svg" },
  {
    code: "PT",
    en: "Portugal",
    mn: "Португал",
    src: "https://flagcdn.com/pt.svg",
  },
  {
    code: "PR",
    en: "Puerto Rico",
    mn: "Пуэрто Рико",
    src: "https://flagcdn.com/pr.svg",
  },
  { code: "QA", en: "Qatar", mn: "Катар", src: "https://flagcdn.com/qa.svg" },
  { code: "RO", en: "Romania", mn: "Румын", src: "https://flagcdn.com/ro.svg" },
  { code: "RW", en: "Rwanda", mn: "Руанда", src: "https://flagcdn.com/rw.svg" },
  {
    code: "RE",
    en: "Réunion",
    mn: "Реюнион",
    src: "https://flagcdn.com/re.svg",
  },
  {
    code: "BL",
    en: "Saint Barthélemy",
    mn: "Сент Бартелми",
    src: "https://flagcdn.com/bl.svg",
  },
  {
    code: "SH",
    en: "Saint Helena",
    mn: "Сент Хелена",
    src: "https://flagcdn.com/sh.svg",
  },
  {
    code: "KN",
    en: "Saint Kitts and Nevis",
    mn: "Сент-Китс ба Невис",
    src: "https://flagcdn.com/kn.svg",
  },
  {
    code: "LC",
    en: "Saint Lucia",
    mn: "Сент Люсия",
    src: "https://flagcdn.com/lc.svg",
  },
  {
    code: "MF",
    en: "Saint Martin",
    mn: "Сент Мартин",
    src: "https://flagcdn.com/mf.svg",
  },
  {
    code: "PM",
    en: "Saint Pierre and Miquelon",
    mn: "Сент Пьер ба Микелон",
    src: "https://flagcdn.com/pm.svg",
  },
  {
    code: "VC",
    en: "Saint Vincent and the Grenadines",
    mn: "Сент Винсент ба Гренадин",
    src: "https://flagcdn.com/vc.svg",
  },
  { code: "WS", en: "Samoa", mn: "Самоа", src: "https://flagcdn.com/ws.svg" },
  {
    code: "SM",
    en: "San Marino",
    mn: "Сан Марино",
    src: "https://flagcdn.com/sm.svg",
  },
  {
    code: "ST",
    en: "São Tomé and Príncipe",
    mn: "Сан-Томе ба Принсип",
    src: "https://flagcdn.com/st.svg",
  },
  {
    code: "SA",
    en: "Saudi Arabia",
    mn: "Саудын Араб",
    src: "https://flagcdn.com/sa.svg",
  },
  {
    code: "SN",
    en: "Senegal",
    mn: "Сенегал",
    src: "https://flagcdn.com/sn.svg",
  },
  { code: "RS", en: "Serbia", mn: "Серб", src: "https://flagcdn.com/rs.svg" },
  {
    code: "SC",
    en: "Seychelles",
    mn: "Сейшел",
    src: "https://flagcdn.com/sc.svg",
  },
  {
    code: "SL",
    en: "Sierra Leone",
    mn: "Сьерра-Леоне",
    src: "https://flagcdn.com/sl.svg",
  },
  {
    code: "SG",
    en: "Singapore",
    mn: "Сингапур",
    src: "https://flagcdn.com/sg.svg",
  },
  {
    code: "SX",
    en: "Sint Maarten",
    mn: "Синт Маартен",
    src: "https://flagcdn.com/sx.svg",
  },
  {
    code: "SK",
    en: "Slovakia",
    mn: "Словак",
    src: "https://flagcdn.com/sk.svg",
  },
  {
    code: "SI",
    en: "Slovenia",
    mn: "Словени",
    src: "https://flagcdn.com/si.svg",
  },
  {
    code: "SB",
    en: "Solomon Islands",
    mn: "Соломон арлууд",
    src: "https://flagcdn.com/sb.svg",
  },
  {
    code: "SO",
    en: "Somalia",
    mn: "Сомали",
    src: "https://flagcdn.com/so.svg",
  },
  {
    code: "GS",
    en: "South Georgia and the South Sandwich Islands",
    mn: "Өмнөд Жоржи ба Өмнөд Сэндвичийн арлууд",
    src: "https://flagcdn.com/gs.svg",
  },
  {
    code: "SS",
    en: "South Sudan",
    mn: "Өмнөд Судан",
    src: "https://flagcdn.com/ss.svg",
  },
  {
    code: "LK",
    en: "Sri Lanka",
    mn: "Шри-Ланка",
    src: "https://flagcdn.com/lk.svg",
  },
  { code: "SD", en: "Sudan", mn: "Судан", src: "https://flagcdn.com/sd.svg" },
  {
    code: "SR",
    en: "Suriname",
    mn: "Суринам",
    src: "https://flagcdn.com/sr.svg",
  },
  {
    code: "SJ",
    en: "Svalbard and Jan Mayen",
    mn: "Свалбард ба Ян Майен",
    src: "https://flagcdn.com/sj.svg",
  },

  {
    code: "TJ",
    en: "Tajikistan",
    mn: "Тажикистан",
    src: "https://flagcdn.com/tj.svg",
  },
  {
    code: "TZ",
    en: "Tanzania",
    mn: "Танзани",
    src: "https://flagcdn.com/tz.svg",
  },
  {
    code: "TH",
    en: "Thailand",
    mn: "Тайланд",
    src: "https://flagcdn.com/th.svg",
  },
  {
    code: "TL",
    en: "Timor-Leste",
    mn: "Тимор-Лесте",
    src: "https://flagcdn.com/tl.svg",
  },
  { code: "TG", en: "Togo", mn: "Того", src: "https://flagcdn.com/tg.svg" },
  {
    code: "TK",
    en: "Tokelau",
    mn: "Токелау",
    src: "https://flagcdn.com/tk.svg",
  },
  { code: "TO", en: "Tonga", mn: "Тонга", src: "https://flagcdn.com/to.svg" },
  {
    code: "TT",
    en: "Trinidad and Tobago",
    mn: "Тринидад ба Тобаго",
    src: "https://flagcdn.com/tt.svg",
  },
  { code: "TN", en: "Tunisia", mn: "Тунис", src: "https://flagcdn.com/tn.svg" },

  {
    code: "TM",
    en: "Turkmenistan",
    mn: "Туркменистан",
    src: "https://flagcdn.com/tm.svg",
  },
  {
    code: "TC",
    en: "Turks and Caicos Islands",
    mn: "Турк ба Кайкос арлууд",
    src: "https://flagcdn.com/tc.svg",
  },
  { code: "TV", en: "Tuvalu", mn: "Тувалу", src: "https://flagcdn.com/tv.svg" },
  { code: "UG", en: "Uganda", mn: "Уганда", src: "https://flagcdn.com/ug.svg" },
  {
    code: "UA",
    en: "Ukraine",
    mn: "Украин",
    src: "https://flagcdn.com/ua.svg",
  },
  {
    code: "AE",
    en: "United Arab Emirates",
    mn: "БНХАУ-ын Эмарат",
    src: "https://flagcdn.com/ae.svg",
  },
  {
    code: "UY",
    en: "Uruguay",
    mn: "Уругвай",
    src: "https://flagcdn.com/uy.svg",
  },
  {
    code: "UZ",
    en: "Uzbekistan",
    mn: "Узбекистан",
    src: "https://flagcdn.com/uz.svg",
  },
  {
    code: "VU",
    en: "Vanuatu",
    mn: "Вануату",
    src: "https://flagcdn.com/vu.svg",
  },
  {
    code: "VA",
    en: "Vatican City",
    mn: "Ватикан хот",
    src: "https://flagcdn.com/va.svg",
  },
  {
    code: "VE",
    en: "Venezuela",
    mn: "Венесуэл",
    src: "https://flagcdn.com/ve.svg",
  },
  {
    code: "VN",
    en: "Vietnam",
    mn: "Вьетнам",
    src: "https://flagcdn.com/vn.svg",
  },
  {
    code: "WF",
    en: "Wallis and Futuna",
    mn: "Уоллис ба Футуна",
    src: "https://flagcdn.com/wf.svg",
  },
  {
    code: "EH",
    en: "Western Sahara",
    mn: "Баруун Сахар",
    src: "https://flagcdn.com/eh.svg",
  },
  { code: "YE", en: "Yemen", mn: "Йемен", src: "https://flagcdn.com/ye.svg" },
  { code: "ZM", en: "Zambia", mn: "Замби", src: "https://flagcdn.com/zm.svg" },
  {
    code: "ZW",
    en: "Zimbabwe",
    mn: "Зимбабве",
    src: "https://flagcdn.com/zw.svg",
  },
];
